name: image_picker_for_web_integration_tests
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker_for_web:
    path: ../
  image_picker_platform_interface:
    git: https://github.com/kumsumit/image_picker_platform_interface.git
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
